"use client"

export function AQIClimateSection() {
  const compounds = [
    {
      name: "PM2.5",
      icon: "🔬",
      description: "Microscopic particles smaller than 2.5 micrometers that penetrate deep into the lungs and bloodstream.",
      effects: "Can cause respiratory problems, aggravate heart diseases, and reduce lung function, especially in children and the elderly.",
      color: "from-amber-500/10 to-orange-500/10",
      borderColor: "border-amber-500/20"
    },
    {
      name: "PM10",
      icon: "💨",
      description: "Respirable particles up to 10 micrometers from dust, pollen, and industrial emissions.",
      effects: "Irritate upper respiratory tract, cause coughing, difficulty breathing, and can aggravate asthma and other lung diseases.",
      color: "from-orange-500/10 to-red-500/10",
      borderColor: "border-orange-500/20"
    },
    {
      name: "Ozone (O₃)",
      icon: "☀️",
      description: "Gas formed by reactions between nitrogen oxides and volatile organic compounds under sunlight.",
      effects: "Irritates lungs, reduces respiratory function, causes coughing and pain when breathing deeply. Aggravates asthma and other lung diseases.",
      color: "from-blue-500/10 to-cyan-500/10",
      borderColor: "border-blue-500/20"
    },
    {
      name: "Nitrogen Dioxide (NO₂)",
      icon: "🚗",
      description: "Reddish-brown gas produced mainly by vehicles and power plants burning fossil fuels.",
      effects: "Inflames airways, reduces resistance to respiratory infections, and worsens conditions like asthma and bronchitis.",
      color: "from-red-500/10 to-pink-500/10",
      borderColor: "border-red-500/20"
    },
    {
      name: "Sulfur Dioxide (SO₂)",
      icon: "🏭",
      description: "Colorless gas with a pungent smell generated by burning coal and oil in industries and power plants.",
      effects: "Causes bronchoconstriction, makes breathing difficult, irritates eyes and throat. People with asthma are especially vulnerable.",
      color: "from-purple-500/10 to-violet-500/10",
      borderColor: "border-purple-500/20"
    },
    {
      name: "Carbon Monoxide (CO)",
      icon: "⚠️",
      description: "Toxic, odorless, and colorless gas produced by incomplete combustion of fuels in vehicles and boilers.",
      effects: "Reduces blood's ability to carry oxygen, causing fatigue, headaches, dizziness, and in severe cases can be fatal.",
      color: "from-gray-500/10 to-slate-500/10",
      borderColor: "border-gray-500/20"
    }
  ]

  return (
    <section id="aqi-section" className="w-full pt-20 md:pt-32 pb-20 md:pb-32 px-5 relative flex flex-col justify-center items-center">
      <div className="w-[400px] h-[400px] absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-primary/5 blur-[120px] z-0" />
      
      <div className="relative z-10 w-full max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="flex flex-col justify-start items-center gap-4 text-center mb-16">
          <h2 className="text-foreground text-4xl md:text-5xl lg:text-[56px] font-semibold leading-tight md:leading-tight lg:leading-[64px] break-words max-w-4xl">
            Air Compounds and Their Impact
          </h2>
          <p className="text-muted-foreground text-base md:text-lg font-medium leading-relaxed break-words max-w-3xl">
            Learn about the main atmospheric pollutants, where they come from, and how they affect your health and your community
          </p>
        </div>

        {/* Compounds Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {compounds.map((compound, index) => (
            <div
              key={index}
              className={`relative overflow-hidden rounded-xl border backdrop-blur-md transition-all duration-300 hover:scale-[1.02] bg-gradient-to-br ${compound.color} ${compound.borderColor} shadow-xl bg-card/60`}
            >
              <div className="p-6 flex flex-col gap-4">
                {/* Header */}
                <div className="flex items-center gap-3">
                  <span className="text-4xl">{compound.icon}</span>
                  <h3 className="text-xl font-semibold text-foreground">{compound.name}</h3>
                </div>

                {/* Description */}
                <div className="space-y-3">
                  <div>
                    <p className="text-sm font-medium text-foreground/90 leading-relaxed">
                      {compound.description}
                    </p>
                  </div>

                  {/* Effects */}
                  <div className="pt-3 border-t border-border">
                    <div className="flex items-start gap-2">
                      <span className="text-primary mt-1 flex-shrink-0">⚕️</span>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        <span className="font-semibold text-foreground">Effects: </span>
                        {compound.effects}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="absolute top-0 right-0 w-20 h-20 bg-gradient-to-bl from-primary/10 to-transparent rounded-bl-3xl" />
            </div>
          ))}
        </div>

        <div className="mt-16 bg-card/50 backdrop-blur-md border border-border rounded-2xl p-8 md:p-10 text-center shadow-xl">
          <div className="flex flex-col items-center gap-4">
            <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center">
              <span className="text-3xl">🌍</span>
            </div>
            <h3 className="text-2xl font-semibold text-foreground">
              Why is it important to monitor air quality?
            </h3>
            <p className="text-muted-foreground text-base max-w-3xl leading-relaxed">
              Prolonged exposure to polluted air can have serious health effects. 
              Monitoring these pollutants allows you to make informed decisions about when to do 
              outdoor activities, use respiratory protection, or stay indoors, 
              especially protecting vulnerable groups such as children, the elderly, and people with 
              pre-existing respiratory or heart conditions.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}